VAGRANT_API_VERSION = "2"
Vagrant.configure(VAGRANT_API_VERSION) do |config|

    config.vm.box = "hashicorp/precise64"

    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network :private_network, ip: "192.168.33.101"

    config.vm.provision :puppet do |puppet|
        puppet.module_path = "modules"
    end

    config.vm.synced_folder "../../app", "/vagrant"

end