Vagrant.configure("2") do |config|

    config.vm.box = "dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    config.vm.synced_folder "../../app", "/vagrant"

    # Provider
    config.vm.provider :aws do |aws, override|

        aws.access_key_id = "YOUR KEY"
        aws.secret_access_key = "YOUR SECRET KEY"
        aws.keypair_name = "KEYPAIR NAME"

        aws.ami = "ami-f0b11187"

        aws.region = "eu-west-1"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = "~/.ssh/vagrant.pem"
        aws.tags = {
        'Name' => 'vagrants'
        }
    end

    config.vm.provision "shell", :inline => <<-SHELL
        apt-get update
        apt-get install -y puppet
    SHELL

    config.vm.provision :puppet do |puppet|
        puppet.module_path = "modules"
    end

end